#spring.application.name=AUTH-SERVICE
#server.port = 8082
#
#spring.datasource.url = jdbc:mySql://localhost:3306/cab_booking_auth?createDatabaseIfNotExist=true
#spring.datasource.username = root
##spring.datasource.password = maneesh_1227
#
#spring.datasource.password = cab_booking
##spring.datasource.password = Jyothsna@2003
#
##spring.datasource.password = SKtagore5004
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
##cabbookingsecrete
#app.jwt-secrete = 705819a89f19aa889354a7b526fb5bedd143beec344fccc73aafd1fdfb0b8b47
#app-jwt-expiration-milliseconds = 604800000
#
## Swagger UI configuration
#springdoc.api-docs.path=/api/auth/v3/api-docs
#springdoc.swagger-ui.path=/api/auth/swagger-ui.html
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha

spring.application.name=AUTH-SERVICE
spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=dev
