#spring.application.name=USER-SERVICE
#server.port=8085
#
#spring.datasource.url = jdbc:mysql://localhost:3306/cab_booking_users?createDatabaseIfNotExist=true
#spring.datasource.username = root
##spring.datasource.password = SKtagore5004
#
#spring.datasource.password=Suresh97@
##spring.datasource.password = Jyothsna@2003
#spring.jpa.hibernate.ddl-auto=update
#
#
#
#management.endpoints.web.exposure.include=*
#
#spring.jpa.show-sql=true
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
## Swagger UI configuration
#springdoc.api-docs.path=/api/users/v3/api-docs
#springdoc.swagger-ui.path=/api/users/swagger-ui.html
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha

spring.application.name=USER-SERVICE
spring.config.import=optional:configserver:http://localhost:8888


